# 1ST

In [1]:
import numpy as np

In [2]:
myarr = np.array([[9, 4 , 4, 5, 354]], np.int64)

In [3]:
myarr

array([[  9,   4,   4,   5, 354]])

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr[0,3]

np.int64(5)

# 2nd

In [7]:
zeros = np.zeros((2,6))

In [8]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
r = np.arange(20)

In [10]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
lspace = np.linspace(1,8,5)

In [46]:
lspace

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

In [43]:
emp = np.empty((6,3))

In [44]:
emp

array([[9.87060687e-312, 5.43472210e-322, 0.00000000e+000],
       [0.00000000e+000, 7.56587583e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 3.98450763e+252],
       [2.25566551e+137, 5.87769019e+135, 1.15874961e-028],
       [3.99009797e+252, 1.06239598e-153, 3.98472821e+252],
       [1.06244660e-153, 9.78750380e+199, 6.97843734e+252]])

In [15]:
emp_like = np.empty_like(lspace)

In [16]:
emp_like

array([1., 2., 3., 4., 5.])

In [17]:
ide = np.identity(4)

In [18]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr = np.arange(99)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [22]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arr.shape

(99,)

In [24]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [27]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
ar.flat

In [29]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [30]:
ar.ndim

2

In [31]:
ar.size


9

In [32]:
ar.nbytes

72

In [33]:
one = np.array([2,5,66,9,0])

In [34]:
one.argmax()

np.int64(2)

In [35]:
ar.max(axis=1)

array([3, 6, 9])

In [36]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [37]:
ar2 = np.array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [38]:
ar**ar2

array([[ 1,  2,  9],
       [ 1,  5, 36],
       [ 1,  8, 81]])